#cloud-config
# create default user
users:
  - name: dms
    shell: /bin/bash
    gecos: Data Manager
    groups: docker
    
# update system
resize_rootfs: True
package_upgrade: True
package_reboot_if_required: True

write_files:
  - path: /home/dms/run.sh
    owner: dms:dms
    permissions: 0777
    content: |
      #!/bin/bash
      set -x
      set -e
      git clone https://github.com/mlgrm/dms
      cd dms
      curl -H 'Metadata-Flavor: Google' \
          http://metadata.google.internal/computeMetadata/v1/instance/attributes/env \
          -o .env
      docker run \
        -v "/var/run/docker.sock:/var/run/docker.sock" \
        -v "$PWD:/$PWD" \
        -w="/$PWD" \
        docker/compose:1.21.2 up -d
      sleep 15
      docker exec superset superset-demo --quiet
    
# get files
runcmd:
  - [ su, -c, "/bin/bash run.sh", -, dms ]
